# Generated by Django 2.2.2 on 2019-07-16 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 15, 41, 4, 152852, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
